name: IPTV Update

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨 0 点 UTC 时间运行
  workflow_dispatch:  # 手动触发workflow

jobs:
  update-iptv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # 可以将 config.py 中的变量配置为环境变量，例如：
      # - name: Set environment variables
      #   run: |
      #     echo "SOURCE_URLS=${{ secrets.SOURCE_URLS }}" >> $GITHUB_ENV
      #     echo "EPG_URLS=${{ secrets.EPG_URLS }}" >> $GITHUB_ENV
      #     echo "ANNOUNCEMENTS=${{ secrets.ANNOUNCEMENTS }}" >> $GITHUB_ENV
      #     echo "IP_VERSION_PRIORITY=${{ secrets.IP_VERSION_PRIORITY }}" >> $GITHUB_ENV
      #     echo "URL_BLACKLIST=${{ secrets.URL_BLACKLIST }}" >> $GITHUB_ENV

      - name: Run IPTV script
        run: python main.py

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes detected"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add live.m3u live.txt function.log
          git commit -m "Update live.m3u, live.txt and function.log"
          git push origin main
